version: '3.8'

services:
  dapps-tutorial-app:
    container_name: dapps-tutorial-container
    build:
      context: .
      dockerfile: Dockerfile
    command: /bin/zsh
    ports:
      - 13040:3000
    volumes:
      # ホスト優先
      - ..:/home/node/dapps-tutorial:cached
    # コンテナ側に仮想端末を置いて実行しているプロセスを用意してあげることによってコンテナを持続させる
    tty: true
    environment: 
      - TZ=Asia/Tokyo
    networks:
      - default

networks: 
  default: